package live.omnisource.tessera.security.rbac;

public enum TesseraPermission {

    // Ops / platform (global)
    TESSERA_OPS_VIEW,
    TESSERA_OPS_ADMIN,

    // RBAC admin (global)
    TESSERA_RBAC_VIEW,
    TESSERA_RBAC_EDIT,

    // Workspace (scoped)
    TESSERA_WORKSPACE_LIST,
    TESSERA_WORKSPACE_VIEW,
    TESSERA_WORKSPACE_CREATE,
    TESSERA_WORKSPACE_DELETE,
    TESSERA_WORKSPACE_MANAGE_MEMBERS,

    // Datastores (scoped)
    TESSERA_DATASTORE_LIST,
    TESSERA_DATASTORE_VIEW,
    TESSERA_DATASTORE_CREATE,
    TESSERA_DATASTORE_UPDATE,
    TESSERA_DATASTORE_DELETE,
    TESSERA_DATASTORE_TEST_CONNECTION,

    // Layers (scoped)
    TESSERA_LAYER_LIST,
    TESSERA_LAYER_VIEW,
    TESSERA_LAYER_CREATE,
    TESSERA_LAYER_UPDATE,
    TESSERA_LAYER_DELETE,
    TESSERA_LAYER_INTROSPECT,

    // Sync (scoped)
    TESSERA_SYNC_VIEW,
    TESSERA_SYNC_RUN,
    TESSERA_SYNC_CONFIGURE
}
